// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaptiveEngine.Service.Domain.Adaptive;

public partial class EstilosAprendizaje
{
    public int IdEstilosAprendizaje { get; set; }

    public string NombreEstilo { get; set; }

    public string Descripcion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<PerfilesEstudiantes> PerfilesEstudiantes { get; set; } = new List<PerfilesEstudiantes>();
}