// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaptiveEngine.Service.Domain.Adaptive;

public partial class ModelosAprendizaje
{
    public int IdModelosAprendizaje { get; set; }

    public string NombreModelo { get; set; }

    public string VersionModelo { get; set; }

    public string ParametrosJson { get; set; }

    public decimal? PrecisionModelo { get; set; }

    public DateTime? FechaEntrenamiento { get; set; }

    public string EstadoModelo { get; set; }

    public sbyte? EsActivo { get; set; }
}