// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaptiveEngine.Service.Domain.Adaptive;

public partial class PerfilesEstudiantes
{
    public int IdPerfilesEstudiantes { get; set; }

    public string IdEstudiante { get; set; }

    public int IdEstilosAprendizaje { get; set; }

    public decimal? NivelActual { get; set; }

    public decimal? VelocidadAprendizaje { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual EstilosAprendizaje IdEstilosAprendizajeNavigation { get; set; }
}