// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaptiveEngine.Service.Domain.Adaptive;

public partial class Recomendaciones
{
    public int IdRecomendaciones { get; set; }

    public string IdEstudiante { get; set; }

    public int IdContenido { get; set; }

    public int IdTiposRecomendacion { get; set; }

    public decimal? PuntajeConfianza { get; set; }

    public DateTime? FechaGeneracion { get; set; }

    public string EstadoRecomendacion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual TiposRecomendacion IdTiposRecomendacionNavigation { get; set; }
}