// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdaptiveEngine.Service.Domain.Adaptive;

public partial class TiposRecomendacion
{
    public int IdTiposRecomendacion { get; set; }

    public string NombreTipo { get; set; }

    public string Descripcion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<Recomendaciones> Recomendaciones { get; set; } = new List<Recomendaciones>();
}