// <auto-generated />
using System;
using AdaptiveEngine.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdaptiveEngine.Service.Migrations
{
    [DbContext(typeof(AdaptiveEngineContext))]
    [Migration("20260603172113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdaptiveEngine.Service.Domain.Entities.EstiloAprendizaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEstilosAprendizaje");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreEstilo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_estilo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("estilos_aprendizaje", (string)null);
                });

            modelBuilder.Entity("AdaptiveEngine.Service.Domain.Entities.PerfilEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPerfilesEstudiantes");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<int>("EstiloAprendizajeId")
                        .HasColumnType("int")
                        .HasColumnName("idEstilosAprendizaje");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<decimal>("NivelActual")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nivel_actual");

                    b.Property<decimal>("VelocidadAprendizaje")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("velocidad_aprendizaje");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EstiloAprendizajeId" }, "fk_perfiles_estudiantes_estilos_aprendizaje_idx");

                    b.ToTable("perfiles_estudiantes", (string)null);
                });

            modelBuilder.Entity("AdaptiveEngine.Service.Domain.Entities.PerfilEstudiante", b =>
                {
                    b.HasOne("AdaptiveEngine.Service.Domain.Entities.EstiloAprendizaje", "EstiloAprendizaje")
                        .WithMany("PerfilesEstudiantes")
                        .HasForeignKey("EstiloAprendizajeId")
                        .IsRequired()
                        .HasConstraintName("fk_perfiles_estudiantes_estilos_aprendizaje");

                    b.Navigation("EstiloAprendizaje");
                });

            modelBuilder.Entity("AdaptiveEngine.Service.Domain.Entities.EstiloAprendizaje", b =>
                {
                    b.Navigation("PerfilesEstudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
