// <auto-generated />
using System;
using LearningAnalytics.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningAnalytics.Service.Migrations
{
    [DbContext(typeof(LearningAnalyticsContext))]
    [Migration("20260603172120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LearningAnalytics.Service.Domain.Entities.EventoAprendizaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEventosAprendizaje");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContenidoId")
                        .HasColumnType("int")
                        .HasColumnName("idContenido");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_evento");

                    b.Property<string>("MetadatosJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("metadatos_json");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("int")
                        .HasColumnName("idTipoEvento");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TipoEventoId" }, "fk_eventos_aprendizaje_TipoEvento_idx");

                    b.ToTable("eventos_aprendizaje", (string)null);
                });

            modelBuilder.Entity("LearningAnalytics.Service.Domain.Entities.MetricaCompromiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMetricasCompromiso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContenidoCompletado")
                        .HasColumnType("int")
                        .HasColumnName("contenido_completado");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_calculo");

                    b.Property<decimal>("PuntajeCompromiso")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("puntaje_compromiso")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int>("TiempoTotalMinutos")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_total_minutos");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("metricas_compromiso", (string)null);
                });

            modelBuilder.Entity("LearningAnalytics.Service.Domain.Entities.SesionAprendizaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSesionesAprendizaje");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadesCompletadas")
                        .HasColumnType("int")
                        .HasColumnName("actividades_completadas");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duracion_minutos");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_inicio");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sesiones_aprendizaje", (string)null);
                });

            modelBuilder.Entity("LearningAnalytics.Service.Domain.Entities.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoEvento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombre_evento");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipo_evento", (string)null);
                });

            modelBuilder.Entity("LearningAnalytics.Service.Domain.Entities.EventoAprendizaje", b =>
                {
                    b.HasOne("LearningAnalytics.Service.Domain.Entities.TipoEvento", "TipoEvento")
                        .WithMany("EventosAprendizaje")
                        .HasForeignKey("TipoEventoId")
                        .IsRequired()
                        .HasConstraintName("fk_eventos_aprendizaje_TipoEvento");

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("LearningAnalytics.Service.Domain.Entities.TipoEvento", b =>
                {
                    b.Navigation("EventosAprendizaje");
                });
#pragma warning restore 612, 618
        }
    }
}
