// <auto-generated />
using System;
using ContentPersonalization.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContentPersonalization.Service.Migrations
{
    [DbContext(typeof(ContentPersonalizationContext))]
    partial class ContentPersonalizationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.ContenidoEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContenidosEducativos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoContenido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_contenido");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("duracion_minutos");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("EtiquetasJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("etiquetas_json");

                    b.Property<int>("NivelDificultadId")
                        .HasColumnType("int")
                        .HasColumnName("idNivelesDificultad");

                    b.Property<int>("TipoContenidoId")
                        .HasColumnType("int")
                        .HasColumnName("idTiposContenido");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlRecurso")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url_recurso");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CodigoContenido" }, "codigo_contenido_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "NivelDificultadId" }, "fk_contenidos_educativos_niveles_dificultad1_idx");

                    b.HasIndex(new[] { "TipoContenidoId" }, "fk_contenidos_educativos_tipos_contenido_idx");

                    b.ToTable("contenidos_educativos", (string)null);
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.EstadoRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEstadosRuta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombre_estado");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("estados_ruta", (string)null);
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.ModeloRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idModelosRuta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContenidoId")
                        .HasColumnType("int")
                        .HasColumnName("idContenido");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("FechaCompletacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_completacion");

                    b.Property<int>("OrdenModulo")
                        .HasColumnType("int")
                        .HasColumnName("orden_modulo");

                    b.Property<int>("RutaAprendizajeId")
                        .HasColumnType("int")
                        .HasColumnName("idRutasAprendizaje");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RutaAprendizajeId" }, "fk_modelos_ruta_rutas_aprendizaje1_idx");

                    b.ToTable("modelos_ruta", (string)null);
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.NivelDificultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNivelesDificultad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreNivel")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombre_nivel");

                    b.Property<decimal>("ValorMaximo")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("valor_maximo");

                    b.Property<decimal>("ValorMinimo")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("niveles_dificultad", (string)null);
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.RutaAprendizaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRutasAprendizaje");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<int>("EstadoRutaId")
                        .HasColumnType("int")
                        .HasColumnName("idEstadosRuta");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreRuta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre_ruta");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EstadoRutaId" }, "fk_rutas_aprendizaje_estados_ruta1_idx");

                    b.ToTable("rutas_aprendizaje", (string)null);
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.TipoContenido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTiposContenido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombre_tipo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipos_contenido", (string)null);
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.ContenidoEducativo", b =>
                {
                    b.HasOne("ContentPersonalization.Service.Domain.Entities.NivelDificultad", "NivelDificultad")
                        .WithMany()
                        .HasForeignKey("NivelDificultadId")
                        .IsRequired()
                        .HasConstraintName("fk_contenidos_educativos_niveles_dificultad1");

                    b.HasOne("ContentPersonalization.Service.Domain.Entities.TipoContenido", "TipoContenido")
                        .WithMany()
                        .HasForeignKey("TipoContenidoId")
                        .IsRequired()
                        .HasConstraintName("fk_contenidos_educativos_tipos_contenido");

                    b.Navigation("NivelDificultad");

                    b.Navigation("TipoContenido");
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.ModeloRuta", b =>
                {
                    b.HasOne("ContentPersonalization.Service.Domain.Entities.RutaAprendizaje", "RutaAprendizaje")
                        .WithMany("ModelosRuta")
                        .HasForeignKey("RutaAprendizajeId")
                        .IsRequired()
                        .HasConstraintName("fk_modelos_ruta_rutas_aprendizaje1");

                    b.Navigation("RutaAprendizaje");
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.RutaAprendizaje", b =>
                {
                    b.HasOne("ContentPersonalization.Service.Domain.Entities.EstadoRuta", "EstadoRuta")
                        .WithMany()
                        .HasForeignKey("EstadoRutaId")
                        .IsRequired()
                        .HasConstraintName("fk_rutas_aprendizaje_estados_ruta1");

                    b.Navigation("EstadoRuta");
                });

            modelBuilder.Entity("ContentPersonalization.Service.Domain.Entities.RutaAprendizaje", b =>
                {
                    b.Navigation("ModelosRuta");
                });
#pragma warning restore 612, 618
        }
    }
}
