// <auto-generated />
using System;
using EducationPlataform.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationPlataform.Service.Migrations
{
    [DbContext(typeof(EducationPlatformContext))]
    [Migration("20260603172025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EducationPlataform.Service.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCursos");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo_curso");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("DuracionHoras")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("duracion_horas");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NivelDificultad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nivel_dificultad");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre_curso");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CodigoCurso" }, "codigo_curso_UNIQUE")
                        .IsUnique();

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("EducationPlataform.Service.Domain.Entities.Estudiante", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<string>("CodigoEstudiante")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo_estudiante");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("segundo_nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "idEstudiante_UNIQUE")
                        .IsUnique();

                    b.ToTable("estudiantes", (string)null);
                });

            modelBuilder.Entity("EducationPlataform.Service.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idInscripciones");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("idCursos");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("EstadoInscripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado_inscripcion")
                        .HasDefaultValueSql("'ACTIVA'");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_inscripcion");

                    b.Property<decimal>("ProgresoPorcentaje")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progreso_porcentaje")
                        .HasDefaultValueSql("'0.00'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CursoId" }, "fk_inscripciones_cursos1_idx");

                    b.HasIndex(new[] { "EstudianteId" }, "fk_inscripciones_usuario_estudiante1_idx");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("EducationPlataform.Service.Domain.Entities.UsuarioEstudiante", b =>
                {
                    b.Property<string>("EstudianteId")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contraseña");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_creacion");

                    b.HasKey("EstudianteId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EstudianteId" }, "fk_usuario_estudiante_estudiantes_idx")
                        .IsUnique();

                    b.ToTable("usuario_estudiante", (string)null);
                });

            modelBuilder.Entity("EducationPlataform.Service.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("EducationPlataform.Service.Domain.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_cursos1");

                    b.HasOne("EducationPlataform.Service.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Inscripciones")
                        .HasForeignKey("EstudianteId")
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_usuario_estudiante1");

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("EducationPlataform.Service.Domain.Entities.UsuarioEstudiante", b =>
                {
                    b.HasOne("EducationPlataform.Service.Domain.Entities.Estudiante", "Estudiante")
                        .WithOne("UsuarioEstudiante")
                        .HasForeignKey("EducationPlataform.Service.Domain.Entities.UsuarioEstudiante", "EstudianteId")
                        .IsRequired()
                        .HasConstraintName("fk_usuario_estudiante_estudiantes");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("EducationPlataform.Service.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("UsuarioEstudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
