services:
# ==================== MICROSERVICIO LEANERNING ====================
  learning-analytics:
    build:
      context: ../src/LearningAnalytics.Service
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=learning_analytics;Uid=root;Pwd=education123;
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
# ==================== MICROSERVICIO ADAPTATIVE ====================
  adaptive-engine:
    build:
      context: ../src/AdaptiveEngine.Service
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=adaptive_engine;Uid=root;Pwd=education123;
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
# ==================== MICROSERVICIO CONTENT ====================
  content-personalization:
    build:
      context: ../src/ContentPersonalization.Service
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=content_personalization;Uid=root;Pwd=education123;
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
# ==================== MICROSERVICIO ASSESSMENT ====================
  assessment:
    build:
      context: ../src/Assessment.Service
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=assessment;Uid=root;Pwd=education123;
    depends_on:
      mysql:
        condition: service_healthy
# ==================== MICROSERVICIO COMPETENCY ====================
  competency-mapping:
    build:
      context: ../src/CompetencyMapping.Service
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=competency_mapping;Uid=root;Pwd=education123;
    depends_on:
      mysql:
        condition: service_healthy

  # ==================== INFRAESTRUCTURA ====================
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: education123
      MYSQL_DATABASE: education_platform
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-peducation123"]
      timeout: 20s
      retries: 10
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3.11-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI

volumes:
  mysql_data: