// <auto-generated />
using System;
using Assessment.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment.Service.Migrations
{
    [DbContext(typeof(AssessmentContext))]
    [Migration("20260603172050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assessment.Service.Domain.Entities.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEvaluaciones");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoEvaluacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_evaluacion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<int>("NivelesDificultadId")
                        .HasColumnType("int")
                        .HasColumnName("idNivelesDificultad");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_estimado_minutos");

                    b.Property<int>("TipoEvaluacionId")
                        .HasColumnType("int")
                        .HasColumnName("idTiposEvaluacion");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NivelesDificultadId" }, "fk_evaluaciones_niveles_dificultad1_idx");

                    b.HasIndex(new[] { "TipoEvaluacionId" }, "fk_evaluaciones_tipos_evaluacion_idx");

                    b.ToTable("evaluaciones", (string)null);
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.Pregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPreguntas");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int")
                        .HasColumnName("idEvaluaciones");

                    b.Property<int>("OrdenPregunta")
                        .HasColumnType("int")
                        .HasColumnName("orden_pregunta");

                    b.Property<string>("PreguntasJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("preguntas_json");

                    b.Property<string>("RespuestaCorrecta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("respuesta_correcta");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_pregunta");

                    b.Property<int>("TipoPreguntaId")
                        .HasColumnType("int")
                        .HasColumnName("idTiposPregunta");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EvaluacionId" }, "fk_preguntas_evaluaciones1_idx");

                    b.HasIndex(new[] { "TipoPreguntaId" }, "fk_preguntas_tipos_pregunta1_idx");

                    b.ToTable("preguntas", (string)null);
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.ResultadoEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idResultadosEvaluacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int")
                        .HasColumnName("idEvaluaciones");

                    b.Property<DateTime>("FechaCompletacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_completacion");

                    b.Property<decimal>("PuntajeMaximo")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("puntaje_maximo");

                    b.Property<decimal>("PuntajeObtenido")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("puntaje_obtenido");

                    b.Property<int>("TiempoEmpleadoMinutos")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_empleado_minutos");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EvaluacionId" }, "fk_resultados_evaluacion_evaluaciones1_idx");

                    b.ToTable("resultados_evaluacion", (string)null);
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.TipoEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTiposEvaluacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombre_tipo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipos_evaluacion", (string)null);
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.TipoPregunta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTiposPregunta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_tipo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tipos_pregunta", (string)null);
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.Evaluacion", b =>
                {
                    b.HasOne("Assessment.Service.Domain.Entities.TipoEvaluacion", "TipoEvaluacion")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("TipoEvaluacionId")
                        .IsRequired()
                        .HasConstraintName("fk_evaluaciones_tipos_evaluacion");

                    b.Navigation("TipoEvaluacion");
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("Assessment.Service.Domain.Entities.Evaluacion", "Evaluacion")
                        .WithMany("Preguntas")
                        .HasForeignKey("EvaluacionId")
                        .IsRequired()
                        .HasConstraintName("fk_preguntas_evaluaciones1");

                    b.HasOne("Assessment.Service.Domain.Entities.TipoPregunta", "TipoPregunta")
                        .WithMany("Preguntas")
                        .HasForeignKey("TipoPreguntaId")
                        .IsRequired()
                        .HasConstraintName("fk_preguntas_tipos_pregunta1");

                    b.Navigation("Evaluacion");

                    b.Navigation("TipoPregunta");
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.ResultadoEvaluacion", b =>
                {
                    b.HasOne("Assessment.Service.Domain.Entities.Evaluacion", "Evaluacion")
                        .WithMany("ResultadosEvaluacion")
                        .HasForeignKey("EvaluacionId")
                        .IsRequired()
                        .HasConstraintName("fk_resultados_evaluacion_evaluaciones1");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.Evaluacion", b =>
                {
                    b.Navigation("Preguntas");

                    b.Navigation("ResultadosEvaluacion");
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.TipoEvaluacion", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("Assessment.Service.Domain.Entities.TipoPregunta", b =>
                {
                    b.Navigation("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
