// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentPersonalization.Service.Domain.Content;

public partial class ContenidosEducativos
{
    public int IdContenidosEducativos { get; set; }

    public string CodigoContenido { get; set; }

    public string Titulo { get; set; }

    public int IdTiposContenido { get; set; }

    public int IdNivelesDificultad { get; set; }

    public string EtiquetasJson { get; set; }

    public string UrlRecurso { get; set; }

    public int? DuracionMinutos { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual NivelesDificultad IdNivelesDificultadNavigation { get; set; }

    public virtual TiposContenido IdTiposContenidoNavigation { get; set; }
}