// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentPersonalization.Service.Domain.Content;

public partial class EstadosRuta
{
    public int IdEstadosRuta { get; set; }

    public string NombreEstado { get; set; }

    public string Descripcion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<RutasAprendizaje> RutasAprendizaje { get; set; } = new List<RutasAprendizaje>();
}