// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentPersonalization.Service.Domain.Content;

public partial class ModelosRuta
{
    public int IdModelosRuta { get; set; }

    public int IdRutasAprendizaje { get; set; }

    public int IdContenido { get; set; }

    public int OrdenModulo { get; set; }

    public DateTime? FechaAsignacion { get; set; }

    public DateTime? FechaCompletacion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual RutasAprendizaje IdRutasAprendizajeNavigation { get; set; }
}