// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentPersonalization.Service.Domain.Content;

public partial class NivelesDificultad
{
    public int IdNivelesDificultad { get; set; }

    public string NombreNivel { get; set; }

    public decimal ValorMinimo { get; set; }

    public decimal ValorMaximo { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<ContenidosEducativos> ContenidosEducativos { get; set; } = new List<ContenidosEducativos>();
}