// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentPersonalization.Service.Domain.Content;

public partial class RutasAprendizaje
{
    public int IdRutasAprendizaje { get; set; }

    public string IdEstudiante { get; set; }

    public string NombreRuta { get; set; }

    public int IdEstadosRuta { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual EstadosRuta IdEstadosRutaNavigation { get; set; }

    public virtual ICollection<ModelosRuta> ModelosRuta { get; set; } = new List<ModelosRuta>();
}