// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ContentPersonalization.Service.Domain.Content;

public partial class TiposContenido
{
    public int IdTiposContenido { get; set; }

    public string NombreTipo { get; set; }

    public string Descripcion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<ContenidosEducativos> ContenidosEducativos { get; set; } = new List<ContenidosEducativos>();
}