// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningAnalytics.Service.Domain.Learning;

public partial class EventosAprendizaje
{
    public int IdEventosAprendizaje { get; set; }

    public string IdEstudiante { get; set; }

    public int IdTipoEvento { get; set; }

    public int IdContenido { get; set; }

    public DateTime? FechaEvento { get; set; }

    public string MetadatosJson { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual TipoEvento IdTipoEventoNavigation { get; set; }
}