// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningAnalytics.Service.Domain.Learning;

public partial class MetricasCompromiso
{
    public int IdMetricasCompromiso { get; set; }

    public string IdEstudiante { get; set; }

    public int? TiempoTotalMinutos { get; set; }

    public int? ContenidoCompletado { get; set; }

    public decimal? PuntajeCompromiso { get; set; }

    public DateTime? FechaCalculo { get; set; }

    public sbyte? EsActivo { get; set; }
}