// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningAnalytics.Service.Domain.Learning;

public partial class SesionesAprendizaje
{
    public int IdSesionesAprendizaje { get; set; }

    public string IdEstudiante { get; set; }

    public DateTime? FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public int? DuracionMinutos { get; set; }

    public int? ActividadesCompletadas { get; set; }

    public sbyte? EsActivo { get; set; }
}