// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearningAnalytics.Service.Domain.Learning;

public partial class TipoEvento
{
    public int IdTipoEvento { get; set; }

    public string NombreEvento { get; set; }

    public string Descripcion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<EventosAprendizaje> EventosAprendizaje { get; set; } = new List<EventosAprendizaje>();
}