// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompetencyMapping.Service.Domain.Competency;

public partial class BrechasAprendizaje
{
    public int IdBrechasAprendizaje { get; set; }

    public string IdEstudiante { get; set; }

    public int IdCompetencias { get; set; }

    public decimal? NivelActual { get; set; }

    public decimal? NivelRequerido { get; set; }

    public int IdNivelesPrioridad { get; set; }

    public DateTime? FechaDeteccion { get; set; }

    public sbyte? EsActiva { get; set; }
}