// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompetencyMapping.Service.Domain.Competency;

public partial class EstadosDominio
{
    public int IdEstadosDominio { get; set; }

    public string NombreEstado { get; set; }

    public string Descripcion { get; set; }

    public sbyte? EsActivo { get; set; }
}