// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompetencyMapping.Service.Domain.Competency;

public partial class MapaCompetenciasEstudiante
{
    public int IdMapaCompetenciasEstudiante { get; set; }

    public string IdEstudiante { get; set; }

    public int IdCompetencias { get; set; }

    public int IdEstadosDominio { get; set; }

    public decimal? NivelDominio { get; set; }

    public decimal? Confianza { get; set; }

    public DateTime? FechaEvaluacion { get; set; }

    public sbyte? EsActivo { get; set; }
}