// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CompetencyMapping.Service.Domain.Competency;

public partial class NivelesPrioridad
{
    public int IdNivelesPrioridad { get; set; }

    public string NombrePrioridad { get; set; }

    public int? ValorPrioridad { get; set; }

    public sbyte? EsActivo { get; set; }
}