// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assessment.Service.Domain.Assessment;

public partial class Evaluaciones
{
    public int IdEvaluaciones { get; set; }

    public string CodigoEvaluacion { get; set; }

    public string Titulo { get; set; }

    public int IdTiposEvaluacion { get; set; }

    public int IdNivelesDificultad { get; set; }

    public int? TiempoEstimadoMinutos { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual TiposEvaluacion IdTiposEvaluacionNavigation { get; set; }

    public virtual ICollection<Preguntas> Preguntas { get; set; } = new List<Preguntas>();

    public virtual ICollection<ResultadosEvaluacion> ResultadosEvaluacion { get; set; } = new List<ResultadosEvaluacion>();
}