// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assessment.Service.Domain.Assessment;

public partial class Preguntas
{
    public int IdPreguntas { get; set; }

    public int IdEvaluaciones { get; set; }

    public string TextoPregunta { get; set; }

    public int IdTiposPregunta { get; set; }

    public string PreguntasJson { get; set; }

    public string RespuestaCorrecta { get; set; }

    public int OrdenPregunta { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual Evaluaciones IdEvaluacionesNavigation { get; set; }

    public virtual TiposPregunta IdTiposPreguntaNavigation { get; set; }
}