// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assessment.Service.Domain.Assessment;

public partial class ResultadosEvaluacion
{
    public int IdResultadosEvaluacion { get; set; }

    public string IdEstudiante { get; set; }

    public int IdEvaluaciones { get; set; }

    public decimal? PuntajeObtenido { get; set; }

    public decimal? PuntajeMaximo { get; set; }

    public int? TiempoEmpleadoMinutos { get; set; }

    public DateTime? FechaCompletacion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual Evaluaciones IdEvaluacionesNavigation { get; set; }
}