// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assessment.Service.Domain.Assessment;

public partial class TiposEvaluacion
{
    public int IdTiposEvaluacion { get; set; }

    public string NombreTipo { get; set; }

    public string Descripcion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<Evaluaciones> Evaluaciones { get; set; } = new List<Evaluaciones>();
}