// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationPlataform.Service.Domain.Education;

public partial class Cursos
{
    public int IdCursos { get; set; }

    public string CodigoCurso { get; set; }

    public string NombreCurso { get; set; }

    public string Descripcion { get; set; }

    public string NivelDificultad { get; set; }

    public string Categoria { get; set; }

    public decimal? DuracionHoras { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual ICollection<Inscripciones> Inscripciones { get; set; } = new List<Inscripciones>();
}