// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationPlataform.Service.Domain.Education;

public partial class Estudiantes
{
    public string IdEstudiante { get; set; }

    public string CodigoEstudiante { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public string Email { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual UsuarioEstudiante UsuarioEstudiante { get; set; }
}