// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationPlataform.Service.Domain.Education;

public partial class Inscripciones
{
    public int IdInscripciones { get; set; }

    public string IdEstudiante { get; set; }

    public int IdCursos { get; set; }

    public DateTime? FechaInscripcion { get; set; }

    public decimal? ProgresoPorcentaje { get; set; }

    public string EstadoInscripcion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual Cursos IdCursosNavigation { get; set; }

    public virtual UsuarioEstudiante IdEstudianteNavigation { get; set; }
}