// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EducationPlataform.Service.Domain.Education;

public partial class UsuarioEstudiante
{
    public string IdEstudiante { get; set; }

    public string Contraseña { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public sbyte? EsActivo { get; set; }

    public virtual Estudiantes IdEstudianteNavigation { get; set; }

    public virtual ICollection<Inscripciones> Inscripciones { get; set; } = new List<Inscripciones>();
}