// <auto-generated />
using System;
using CompetencyMapping.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompetencyMapping.Service.Migrations
{
    [DbContext(typeof(CompetencyMappingContext))]
    partial class CompetencyMappingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompetencyMapping.Service.Domain.Entities.BrechaAprendizaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBrechasAprendizaje");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int")
                        .HasColumnName("idCompetencias");

                    b.Property<bool>("EsActiva")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activa");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime>("FechaDeteccion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_deteccion");

                    b.Property<decimal>("NivelActual")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nivel_actual");

                    b.Property<int>("NivelPrioridadId")
                        .HasColumnType("int")
                        .HasColumnName("idNivelesPrioridad");

                    b.Property<decimal>("NivelRequerido")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nivel_requerido");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompetenciaId" }, "fk_brechas_aprendizaje_Competencias1_idx");

                    b.HasIndex(new[] { "NivelPrioridadId" }, "fk_brechas_aprendizaje_niveles_prioridad1_idx");

                    b.ToTable("brechas_aprendizaje", (string)null);
                });

            modelBuilder.Entity("CompetencyMapping.Service.Domain.Entities.CategoriaCompetencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoriasCompetencia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_categoria");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("categorias_competencia", (string)null);
                });

            modelBuilder.Entity("CompetencyMapping.Service.Domain.Entities.EstadoDominio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEstadosDominio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombre_estado");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("estados_dominio", (string)null);
                });

            modelBuilder.Entity("CompetencyMapping.Service.Domain.Entities.MapaCompetenciaEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMapaCompetenciasEstudiante");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int")
                        .HasColumnName("idCompetencias");

                    b.Property<decimal>("Confianza")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("confianza");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<int>("EstadoDominioId")
                        .HasColumnType("int")
                        .HasColumnName("idEstadosDominio");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("idEstudiante");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("timestamp")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<decimal>("NivelDominio")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("nivel_dominio");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompetenciaId" }, "fk_mapa_competencias_estudiante_Competencias1_idx");

                    b.HasIndex(new[] { "EstadoDominioId" }, "fk_mapa_competencias_estudiante_estados_dominio1_idx");

                    b.ToTable("mapa_competencias_estudiante", (string)null);
                });

            modelBuilder.Entity("CompetencyMapping.Service.Domain.Entities.NivelPrioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idNivelesPrioridad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsActivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_activo");

                    b.Property<string>("NombrePrioridad")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombre_prioridad");

                    b.Property<int>("ValorPrioridad")
                        .HasColumnType("int")
                        .HasColumnName("valor_prioridad");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("niveles_prioridad", (string)null);
                });

            modelBuilder.Entity("CompetencyMapping.Service.Domain.Entities.BrechaAprendizaje", b =>
                {
                    b.HasOne("CompetencyMapping.Service.Domain.Entities.NivelPrioridad", "NivelPrioridad")
                        .WithMany()
                        .HasForeignKey("NivelPrioridadId")
                        .IsRequired()
                        .HasConstraintName("fk_brechas_aprendizaje_niveles_prioridad1");

                    b.Navigation("NivelPrioridad");
                });

            modelBuilder.Entity("CompetencyMapping.Service.Domain.Entities.MapaCompetenciaEstudiante", b =>
                {
                    b.HasOne("CompetencyMapping.Service.Domain.Entities.EstadoDominio", "EstadoDominio")
                        .WithMany()
                        .HasForeignKey("EstadoDominioId")
                        .IsRequired()
                        .HasConstraintName("fk_mapa_competencias_estudiante_estados_dominio1");

                    b.Navigation("EstadoDominio");
                });
#pragma warning restore 612, 618
        }
    }
}
